{% set name = "casq" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/casq-{{ version }}.tar.gz
  sha256: 880f1d090d99e4b347d4fbe77545228d2e67dbd85ffaee8c06e8201239d1fefb

build:
  entry_points:
    - casq = casq.celldesigner2qual:main
  noarch: python
  script:
    # handle interaction between hatch and conda-smithy's .gitignore
    - echo "[tool.hatch.build.targets.wheel]"   >> pyproject.toml
    - echo "ignore-vcs = true"                  >> pyproject.toml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - pip
  run:
    - python >={{ python_min }}
    - loguru >=0.2.5
    - networkx >=2.2

test:
  imports:
    - casq
  commands:
    - pip check
    - casq --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://soliman.gitlabpages.inria.fr/casq/
  summary: 'CaSQ: Celldesigner as Sbml-Qual'
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://casq.readthedocs.io/en/latest/
  dev_url: https://gitlab.inria.fr/soliman/casq/

extra:
  recipe-maintainers:
    - soli
